# Generated by Django 4.1.6 on 2024-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_div_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='suborganization',
            name='org_id',
        ),
    ]
