# Generated by Django 4.1.6 on 2024-08-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationApp', '0003_remove_division_id_remove_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborganization',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrganizationApp.organization'),
            preserve_default=False,
        ),
    ]
