# Generated by Django 4.1.6 on 2024-08-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationApp', '0004_suborganization_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborganization',
            name='org_id',
        ),
    ]
