# Generated by Django 4.1.6 on 2024-08-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationApp', '0006_suborganization_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='sub_org',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='OrganizationApp.suborganization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_div',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='OrganizationApp.subdivision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdivision',
            name='div',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='OrganizationApp.division'),
            preserve_default=False,
        ),
    ]
